// SwiftX - screenshot capture and sharing for macOS
// Copyright (c) 2026 RetroHazard
// Contains code derived from ShareX, Copyright (c) 2007-2026 ShareX Team
// Licensed under GPL v3 - see /LICENSE.txt
//
// Image effects editor and beautifier windows (C# ImageEffectsForm /
// ImageBeautifierForm). The parameter form is generated by reflecting the
// effect struct, so all 51 effects share one editor: each edit is written
// into the effect's C#-shaped JSON and re-decoded.

import AppKit
import CaptureKit
import EffectsKit
import SharedKit
import SwiftUI
import ToolsKit
import UniformTypeIdentifiers

@MainActor
enum ImageEffectsWindows {
    static func showEditor() {
        ToolWindows.present(title: "Image Effects", resizable: true,
                            content: ImageEffectsEditorView(store: ImageEffectsStore.shared))
    }

    /// C# ImageBeautifierTool: pick an image, tune, copy/save.
    static func showBeautifier() {
        let panel = NSOpenPanel()
        panel.allowedContentTypes = [.image]
        NSApp.activate(ignoringOtherApps: true)
        guard panel.runModal() == .OK, let url = panel.url,
              let image = ImageLoader.load(url: url) else { return }
        ToolWindows.present(title: "Image Beautifier — \(url.lastPathComponent)", resizable: true,
                            content: ImageBeautifierView(store: ImageEffectsStore.shared, source: image))
    }
}

// MARK: - Effects editor

struct ImageEffectsEditorView: View {
    @ObservedObject var store: ImageEffectsStore
    @State private var selectedEffectIndex: Int?
    @State private var preview: CGImage?

    var body: some View {
        HSplitView {
            presetsPane.frame(minWidth: 170, maxWidth: 240)
            chainPane.frame(minWidth: 220, maxWidth: 300)
            detailPane.frame(minWidth: 340, maxHeight: .infinity)
        }
        .frame(minWidth: 860, minHeight: 540)
        .onAppear { refreshPreview() }
    }

    private var presetsPane: some View {
        VStack(spacing: 8) {
            List(selection: Binding(
                get: { store.presets.indices.contains(store.selectedIndex) ? store.selectedIndex : nil },
                set: { index in
                    store.selectedIndex = index ?? 0
                    selectedEffectIndex = nil
                    store.save()
                    refreshPreview()
                }
            )) {
                ForEach(store.presets.indices, id: \.self) { index in
                    Text(store.presets[index].name.isEmpty ? "Preset \(index + 1)" : store.presets[index].name)
                        .tag(index)
                }
            }
            if store.presets.indices.contains(store.selectedIndex) {
                TextField("Preset name", text: Binding(
                    get: { store.presets[store.selectedIndex].name },
                    set: { name in mutatePreset { $0.name = name } }
                ))
                .textFieldStyle(.roundedBorder)
            }
            HStack {
                Button {
                    store.presets.append(ImageEffectPreset(name: "Preset \(store.presets.count + 1)"))
                    store.selectedIndex = store.presets.count - 1
                    selectedEffectIndex = nil
                    store.save()
                    refreshPreview()
                } label: { Image(systemName: "plus") }
                Button {
                    guard store.presets.indices.contains(store.selectedIndex) else { return }
                    store.presets.remove(at: store.selectedIndex)
                    store.selectedIndex = min(store.selectedIndex, store.presets.count - 1)
                    selectedEffectIndex = nil
                    store.save()
                    refreshPreview()
                } label: { Image(systemName: "minus") }
                Spacer()
                Button("Import…") { importPreset() }
                Button("Export…") { exportPreset() }
                    .disabled(!store.presets.indices.contains(store.selectedIndex))
            }
            .controlSize(.small)
        }
        .padding(8)
    }

    private var chainPane: some View {
        VStack(spacing: 8) {
            List(selection: $selectedEffectIndex) {
                if let preset = store.selectedPreset {
                    ForEach(preset.effects.indices, id: \.self) { index in
                        HStack {
                            Toggle("", isOn: Binding(
                                get: { preset.effects[index].enabled },
                                set: { on in mutatePreset { $0.effects[index].enabled = on } }
                            ))
                            .labelsHidden()
                            Text(preset.effects[index].displayName)
                        }
                        .tag(index)
                    }
                }
            }
            HStack {
                Menu {
                    ForEach(EffectCategory.allCases, id: \.rawValue) { category in
                        Section(category.rawValue) {
                            ForEach(EffectRegistry.types(in: category).map { $0.typeName }, id: \.self) { name in
                                Button(name) { addEffect(named: name) }
                            }
                        }
                    }
                } label: { Image(systemName: "plus") }
                .menuStyle(.borderlessButton)
                .frame(width: 40)
                Button {
                    guard let index = selectedEffectIndex,
                          store.selectedPreset?.effects.indices.contains(index) == true else { return }
                    mutatePreset { $0.effects.remove(at: index) }
                    let count = store.selectedPreset?.effects.count ?? 0
                    selectedEffectIndex = count > 0 ? min(index, count - 1) : nil
                } label: { Image(systemName: "minus") }
                Spacer()
                Button { moveEffect(by: -1) } label: { Image(systemName: "chevron.up") }
                Button { moveEffect(by: 1) } label: { Image(systemName: "chevron.down") }
            }
            .controlSize(.small)
            .disabled(store.selectedPreset == nil)
        }
        .padding(8)
    }

    private var detailPane: some View {
        VSplitView {
            Group {
                if let index = selectedEffectIndex,
                   let preset = store.selectedPreset, preset.effects.indices.contains(index) {
                    EffectParameterForm(effect: preset.effects[index]) { updated in
                        mutatePreset { $0.effects[index] = updated }
                    }
                    // the form rebuilds whenever another effect row is picked
                    .id(index)
                } else {
                    Text("Select an effect to edit its parameters.")
                        .foregroundStyle(.secondary)
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                }
            }
            .frame(minHeight: 220)
            previewPane.frame(minHeight: 160)
        }
    }

    private var previewPane: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text("Preview").font(.caption).foregroundStyle(.secondary)
            Group {
                if let preview {
                    Image(decorative: preview, scale: 2)
                        .resizable()
                        .aspectRatio(contentMode: .fit)
                } else {
                    ProgressView()
                }
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .background(CheckerboardBackground())
        }
        .padding(8)
    }

    // MARK: mutations

    private func mutatePreset(_ body: (inout ImageEffectPreset) -> Void) {
        guard store.presets.indices.contains(store.selectedIndex) else { return }
        body(&store.presets[store.selectedIndex])
        store.save()
        refreshPreview()
    }

    private func addEffect(named name: String) {
        guard let type = EffectRegistry.type(named: name) else { return }
        mutatePreset { $0.effects.append(type.init()) }
        selectedEffectIndex = (store.selectedPreset?.effects.count ?? 1) - 1
    }

    private func moveEffect(by delta: Int) {
        guard let index = selectedEffectIndex,
              let preset = store.selectedPreset,
              preset.effects.indices.contains(index),
              preset.effects.indices.contains(index + delta) else { return }
        mutatePreset { $0.effects.swapAt(index, index + delta) }
        selectedEffectIndex = index + delta
    }

    private func importPreset() {
        let panel = NSOpenPanel()
        var types = [UTType.json]
        if let sxie = UTType(filenameExtension: "sxie") { types.insert(sxie, at: 0) }
        panel.allowedContentTypes = types
        guard panel.runModal() == .OK, let url = panel.url else { return }
        do {
            let preset = url.pathExtension.lowercased() == "json"
                ? try ImageEffectPreset.fromConfigJSON(Data(contentsOf: url))
                : try ImageEffectPreset.importSXIE(from: url)
            store.presets.append(preset)
            store.selectedIndex = store.presets.count - 1
            selectedEffectIndex = nil
            store.save()
            refreshPreview()
        } catch {
            Notifier.notify(title: "Import failed", body: error.localizedDescription)
        }
    }

    private func exportPreset() {
        guard let preset = store.selectedPreset else { return }
        let panel = NSSavePanel()
        panel.nameFieldStringValue = (preset.name.isEmpty ? "Preset" : preset.name) + ".sxie"
        guard panel.runModal() == .OK, let url = panel.url else { return }
        do {
            try preset.exportSXIE(to: url)
        } catch {
            Notifier.notify(title: "Export failed", body: error.localizedDescription)
        }
    }

    // MARK: preview

    private func refreshPreview() {
        // ponytail: synchronous apply on a small sample; background it if a chain ever feels slow
        preview = store.selectedPreset?.apply(Self.sample) ?? Self.sample
    }

    private static let sample: CGImage = EffectSample.make()
}

/// A small screenshot-like sample the preview runs the chain on.
enum EffectSample {
    static func make() -> CGImage {
        let width = 400, height = 250
        let context = CGContext(
            data: nil, width: width, height: height, bitsPerComponent: 8, bytesPerRow: 0,
            space: CGColorSpace(name: CGColorSpace.sRGB)!,
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        )!
        context.setFillColor(CGColor(srgbRed: 0.96, green: 0.96, blue: 0.98, alpha: 1))
        context.fill(CGRect(x: 0, y: 0, width: width, height: height))
        // "title bar" and colored blocks give the filters something to chew on
        context.setFillColor(CGColor(srgbRed: 0.27, green: 0.47, blue: 0.76, alpha: 1))
        context.fill(CGRect(x: 0, y: height - 40, width: width, height: 40))
        for (index, color) in [(1.0, 0.3, 0.3), (0.3, 0.75, 0.4), (1.0, 0.75, 0.2)].enumerated() {
            context.setFillColor(CGColor(srgbRed: color.0, green: color.1, blue: color.2, alpha: 1))
            context.fillEllipse(in: CGRect(x: 20 + index * 70, y: 60, width: 50, height: 50))
        }
        let text = NSAttributedString(string: "SwiftX", attributes: [
            .font: NSFont.boldSystemFont(ofSize: 28), .foregroundColor: NSColor.darkGray
        ])
        let nsContext = NSGraphicsContext(cgContext: context, flipped: false)
        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = nsContext
        text.draw(at: NSPoint(x: 20, y: 140))
        NSGraphicsContext.restoreGraphicsState()
        return context.makeImage()!
    }
}

struct CheckerboardBackground: View {
    var body: some View {
        Canvas { context, size in
            let cell: CGFloat = 8
            for row in 0..<Int(size.height / cell + 1) {
                for column in 0..<Int(size.width / cell + 1) where (row + column).isMultiple(of: 2) {
                    context.fill(
                        Path(CGRect(x: CGFloat(column) * cell, y: CGFloat(row) * cell, width: cell, height: cell)),
                        with: .color(Color(white: 0.85))
                    )
                }
            }
        }
        .background(Color(white: 0.95))
    }
}

// MARK: - Generic parameter form

/// One editor for all effects: reflects the struct's fields, renders a row
/// per supported type, writes edits into the effect's JSON dict and
/// re-decodes through the same path .sxie imports use.
struct EffectParameterForm: View {
    let effect: any ImageEffecting
    let onChange: (any ImageEffecting) -> Void

    var body: some View {
        Form {
            Section(type(of: effect).typeName) {
                ForEach(fields, id: \.key) { field in
                    row(for: field)
                }
            }
        }
        .formStyle(.grouped)
    }

    private struct Field {
        let key: String
        let value: Any
    }

    private var fields: [Field] {
        Mirror(reflecting: effect).children.compactMap { child in
            guard let label = child.label, label != "enabled" else { return nil }
            return Field(key: label, value: child.value)
        }
    }

    /// Writes one field back through the JSON round-trip.
    private func update(_ key: String, to jsonValue: Any) {
        guard var dict = try? effect.encodeWithType() else { return }
        dict[key.prefix(1).uppercased() + key.dropFirst()] = jsonValue
        guard let type = EffectRegistry.type(named: type(of: effect).typeName),
              let updated = try? type.decode(mergedWith: dict) else { return }
        onChange(updated)
    }

    private func label(_ key: String) -> String {
        // camelCase -> Title Case ("cornerRadius" -> "Corner Radius")
        var out = ""
        for character in key {
            if character.isUppercase, !out.isEmpty { out.append(" ") }
            out.append(out.isEmpty ? Character(character.uppercased()) : character)
        }
        return out
    }

    @ViewBuilder
    private func row(for field: Field) -> some View {
        let title = label(field.key)
        switch field.value {
        case let value as Bool:
            Toggle(title, isOn: binding(field.key, value) { $0 })
        case let value as Int:
            TextField(title, value: binding(field.key, value) { $0 }, format: .number)
        case let value as Float:
            TextField(title, value: binding(field.key, value) { Double($0) }, format: .number)
        case let value as Double:
            TextField(title, value: binding(field.key, value) { $0 }, format: .number)
        case let value as String:
            TextField(title, text: binding(field.key, value) { $0 }, axis: .vertical)
        case let value as CSColor:
            ColorPicker(title, selection: Binding(
                get: { Color(nsColor: value.nsColor) },
                set: { update(field.key, to: csColor(from: $0).stringValue) }
            ), supportsOpacity: true)
        case let value as CSPoint:
            LabeledContent(title) {
                numberField("X", value.x) { update(field.key, to: "\($0), \(value.y)") }
                numberField("Y", value.y) { update(field.key, to: "\(value.x), \($0)") }
            }
        case let value as CSSize:
            LabeledContent(title) {
                numberField("W", value.width) { update(field.key, to: "\($0), \(value.height)") }
                numberField("H", value.height) { update(field.key, to: "\(value.width), \($0)") }
            }
        case let value as CSPadding:
            LabeledContent(title) {
                numberField("L", value.left) { update(field.key, to: "\($0), \(value.top), \(value.right), \(value.bottom)") }
                numberField("T", value.top) { update(field.key, to: "\(value.left), \($0), \(value.right), \(value.bottom)") }
                numberField("R", value.right) { update(field.key, to: "\(value.left), \(value.top), \($0), \(value.bottom)") }
                numberField("B", value.bottom) { update(field.key, to: "\(value.left), \(value.top), \(value.right), \($0)") }
            }
        case let value as CSFont:
            fontRow(title, key: field.key, font: value)
        case let value as AnchorSides:
            anchorRow(title, key: field.key, sides: value)
        case let value as ContentAlignment:
            Picker(title, selection: binding(field.key, value) { $0.rawValue }) {
                ForEach(ContentAlignment.allCases, id: \.rawValue) { alignment in
                    Text(label("\(alignment)")).tag(alignment)
                }
            }
        case let value as DashStyle:
            Picker(title, selection: binding(field.key, value) { $0.rawValue }) {
                Text("Solid").tag(DashStyle.solid)
                Text("Dash").tag(DashStyle.dash)
                Text("Dot").tag(DashStyle.dot)
                Text("Dash Dot").tag(DashStyle.dashDot)
                Text("Dash Dot Dot").tag(DashStyle.dashDotDot)
            }
        case let value as GradientType:
            gradientTypePicker(title, selection: binding(field.key, value) { $0.rawValue })
        case let value as GradientInfo:
            gradientRow(title, key: field.key, gradient: value)
        default:
            LabeledContent(title) {
                Text(String(describing: field.value)).foregroundStyle(.secondary)
            }
        }
    }

    /// Binding that routes sets through the JSON round-trip. `encode` maps
    /// the Swift value to its JSON representation.
    private func binding<T>(_ key: String, _ current: T, encode: @escaping (T) -> Any) -> Binding<T> {
        Binding(get: { current }, set: { update(key, to: encode($0)) })
    }

    private func numberField(_ short: String, _ value: Int, commit: @escaping (Int) -> Void) -> some View {
        TextField(short, value: Binding(get: { value }, set: commit), format: .number)
            .frame(width: 56)
            .multilineTextAlignment(.trailing)
    }

    private func csColor(from color: Color) -> CSColor {
        guard let srgb = NSColor(color).usingColorSpace(.sRGB) else { return .black }
        return CSColor(r: UInt8((srgb.redComponent * 255).rounded()),
                       g: UInt8((srgb.greenComponent * 255).rounded()),
                       b: UInt8((srgb.blueComponent * 255).rounded()),
                       a: UInt8((srgb.alphaComponent * 255).rounded()))
    }

    private func fontString(_ font: CSFont) -> String {
        var styles: [String] = []
        if font.bold { styles.append("Bold") }
        if font.italic { styles.append("Italic") }
        let suffix = styles.isEmpty ? "" : ", style=\(styles.joined(separator: ", "))"
        return "\(font.family), \(font.size.formatted(.number.precision(.fractionLength(0...2))))pt\(suffix)"
    }

    private func fontRow(_ title: String, key: String, font: CSFont) -> some View {
        LabeledContent(title) {
            TextField("Family", text: Binding(
                get: { font.family },
                set: { var f = font; f.family = $0; update(key, to: fontString(f)) }
            ))
            .frame(width: 120)
            TextField("Size", value: Binding(
                get: { font.size },
                set: { var f = font; f.size = $0; update(key, to: fontString(f)) }
            ), format: .number)
            .frame(width: 48)
            Toggle("B", isOn: Binding(
                get: { font.bold },
                set: { var f = font; f.bold = $0; update(key, to: fontString(f)) }
            ))
            Toggle("I", isOn: Binding(
                get: { font.italic },
                set: { var f = font; f.italic = $0; update(key, to: fontString(f)) }
            ))
        }
    }

    private func anchorRow(_ title: String, key: String, sides: AnchorSides) -> some View {
        LabeledContent(title) {
            ForEach([("Top", AnchorSides.top), ("Bottom", .bottom), ("Left", .left), ("Right", .right)],
                    id: \.0) { name, side in
                Toggle(name, isOn: Binding(
                    get: { sides.contains(side) },
                    set: { on in
                        var updated = sides
                        if on { updated.insert(side) } else { updated.remove(side) }
                        update(key, to: updated.rawValue)
                    }
                ))
            }
        }
    }

    private func gradientTypePicker(_ title: String, selection: Binding<GradientType>) -> some View {
        Picker(title, selection: selection) {
            Text("Horizontal").tag(GradientType.horizontal)
            Text("Vertical").tag(GradientType.vertical)
            Text("Forward Diagonal").tag(GradientType.forwardDiagonal)
            Text("Backward Diagonal").tag(GradientType.backwardDiagonal)
        }
    }

    private func gradientJSON(_ gradient: GradientInfo) -> [String: Any] {
        [
            "Type": gradient.type.rawValue,
            "Colors": gradient.colors.map { ["Color": $0.color.stringValue, "Location": $0.location] }
        ]
    }

    private func gradientRow(_ title: String, key: String, gradient: GradientInfo) -> some View {
        DisclosureGroup(title) {
            gradientTypePicker("Type", selection: Binding(
                get: { gradient.type },
                set: { var g = gradient; g.type = $0; update(key, to: gradientJSON(g)) }
            ))
            ForEach(gradient.colors.indices, id: \.self) { index in
                HStack {
                    ColorPicker("", selection: Binding(
                        get: { Color(nsColor: gradient.colors[index].color.nsColor) },
                        set: {
                            var g = gradient
                            g.colors[index].color = csColor(from: $0)
                            update(key, to: gradientJSON(g))
                        }
                    ), supportsOpacity: true)
                    .labelsHidden()
                    TextField("Location %", value: Binding(
                        get: { gradient.colors[index].location },
                        set: {
                            var g = gradient
                            g.colors[index].location = $0
                            update(key, to: gradientJSON(g))
                        }
                    ), format: .number)
                    .frame(width: 56)
                    Button {
                        var g = gradient
                        g.colors.remove(at: index)
                        update(key, to: gradientJSON(g))
                    } label: { Image(systemName: "minus.circle") }
                    .buttonStyle(.borderless)
                }
            }
            Button("Add Stop") {
                var g = gradient
                g.colors.append(GradientStop(color: .black, location: 100))
                update(key, to: gradientJSON(g))
            }
        }
    }
}

// MARK: - Beautifier

struct ImageBeautifierView: View {
    @ObservedObject var store: ImageEffectsStore
    let source: CGImage
    @State private var preview: CGImage?

    /// Preview renders on a downscaled copy so the sliders stay live.
    private var previewSource: CGImage {
        guard source.width > 700 else { return source }
        var resize = ResizeEffect()
        resize.width = 700
        resize.height = 0
        return resize.apply(source)
    }

    var body: some View {
        HSplitView {
            controls.frame(width: 320)
            previewPane.frame(minWidth: 420, maxWidth: .infinity, maxHeight: .infinity)
        }
        .frame(minWidth: 780, minHeight: 480)
        .onAppear { refresh() }
    }

    private var controls: some View {
        Form {
            Section("Layout") {
                intSlider("Margin", value: \.margin, range: 0...300)
                intSlider("Padding", value: \.padding, range: 0...200)
                Toggle("Smart padding", isOn: bound(\.smartPadding))
                intSlider("Rounded corner", value: \.roundedCorner, range: 0...100)
            }
            Section("Shadow") {
                intSlider("Radius", value: \.shadowRadius, range: 0...100)
                intSlider("Opacity", value: \.shadowOpacity, range: 0...100)
                intSlider("Distance", value: \.shadowDistance, range: 0...100)
                intSlider("Angle", value: \.shadowAngle, range: 0...360)
            }
            Section("Background") {
                Picker("Type", selection: bound(\.backgroundType)) {
                    Text("Gradient").tag(0)
                    Text("Color").tag(1)
                    Text("Image").tag(2)
                    Text("Transparent").tag(4)
                }
                if store.beautifier.backgroundType == 1 {
                    ColorPicker("Color", selection: Binding(
                        get: { Color(nsColor: store.beautifier.backgroundColor.nsColor) },
                        set: { color in
                            guard let srgb = NSColor(color).usingColorSpace(.sRGB) else { return }
                            store.beautifier.backgroundColor = CSColor(
                                r: UInt8((srgb.redComponent * 255).rounded()),
                                g: UInt8((srgb.greenComponent * 255).rounded()),
                                b: UInt8((srgb.blueComponent * 255).rounded()))
                            changed()
                        }
                    ))
                }
                if store.beautifier.backgroundType == 2 {
                    LabeledContent("Image") {
                        Text(store.beautifier.backgroundImageFilePath.isEmpty
                             ? "None" : (store.beautifier.backgroundImageFilePath as NSString).lastPathComponent)
                            .foregroundStyle(.secondary).lineLimit(1).truncationMode(.middle)
                        Button("Browse…") {
                            let panel = NSOpenPanel()
                            panel.allowedContentTypes = [.image]
                            if panel.runModal() == .OK, let url = panel.url {
                                store.beautifier.backgroundImageFilePath = url.path
                                changed()
                            }
                        }
                    }
                }
            }
            Section {
                HStack {
                    Button("Copy") { ImageWriter.copyToClipboard(rendered()) }
                    Button("Save…") {
                        let panel = NSSavePanel()
                        panel.nameFieldStringValue = "beautified.png"
                        if panel.runModal() == .OK, let url = panel.url {
                            try? ImageWriter.writePNG(rendered(), to: url)
                        }
                    }
                    Button("Reset") {
                        store.beautifier = ImageBeautifierOptions()
                        changed()
                    }
                }
            }
        }
        .formStyle(.grouped)
    }

    private var previewPane: some View {
        Group {
            if let preview {
                Image(decorative: preview, scale: 2)
                    .resizable()
                    .aspectRatio(contentMode: .fit)
                    .padding(8)
            } else {
                ProgressView()
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(CheckerboardBackground())
    }

    private func bound<T>(_ keyPath: WritableKeyPath<ImageBeautifierOptions, T>) -> Binding<T> {
        Binding(
            get: { store.beautifier[keyPath: keyPath] },
            set: { store.beautifier[keyPath: keyPath] = $0; changed() }
        )
    }

    private func intSlider(_ title: String, value keyPath: WritableKeyPath<ImageBeautifierOptions, Int>,
                           range: ClosedRange<Double>) -> some View {
        LabeledContent(title) {
            Slider(value: Binding(
                get: { Double(store.beautifier[keyPath: keyPath]) },
                set: { store.beautifier[keyPath: keyPath] = Int($0.rounded()); changed() }
            ), in: range)
            Text("\(store.beautifier[keyPath: keyPath])")
                .monospacedDigit().frame(width: 36, alignment: .trailing)
        }
    }

    private func changed() {
        store.save()
        refresh()
    }

    private func refresh() {
        // ponytail: synchronous render of a <=700px preview; background it if it ever stutters
        preview = ImageBeautifier.render(previewSource, options: store.beautifier)
    }

    private func rendered() -> CGImage {
        ImageBeautifier.render(source, options: store.beautifier)
    }
}
