name: macOS Swift

on:
  push:
    paths:
      - "Sources/**"
      - "Tests/**"
      - "Package.swift"
      - "Scripts/**"
      - "Resources/**"
      - "Assets/**"
      - "Casks/**"
      - ".github/workflows/macos-swift.yml"
  pull_request:
    paths:
      - "Sources/**"
      - "Tests/**"
      - "Package.swift"
      - "Scripts/**"
      - "Resources/**"
      - "Assets/**"
      - "Casks/**"
      - ".github/workflows/macos-swift.yml"

jobs:
  build-and-test:
    if: github.repository == 'RetroHazard/SwiftX'
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: swift build
      - name: Test
        run: swift test
      - name: Bundle app
        run: ./Scripts/make-app.sh
